apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: donot-hardcode-password-in-env-vars
  annotations:
    policies.kyverno.io/title: Disallow Passwords from Env Vars
    policies.kyverno.io/category: Sample, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Secret
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/description: >-
      Passwords should not be hardcoded in environment variables, This policy disallows using Secrets which hardcoded as environment variables.      
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: donot-hardcode-password-in-env-vars
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - kyverno-test
    validate:
      message: "passwords should not be hardcoded in env"
      pattern:
        spec:
          containers:
          - name: "*"
            =(env):
            - X(value): "*"
